esphome:
  name: salacia

esp32:
  # board: esp32doit-devkit-v1
  board: node32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rabbit-Hutch Fallback Hotspot"
    password: !secret hot_password

captive_portal:
    
web_server:
  port: 80 
  version: 1
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Sensor IP address"
    ssid:
      name: "Sensor SSID"
  - platform: version
    name: "Sensor ESPHome Version"

# main
i2c:
  sda: 21
  scl: 22
  scan: false
  id: bus_a
# frequency: 100kHz

# measure salt storage level
sensor:
  - platform: vl53l0x
    name: "VL53L0x Distance"
    address: 0x29
    update_interval: 60s
    long_range: true

# two GPIO switches to read the status of the water level sensors
switch:
  - platform: gpio
    pin:
      number: GPIOXX
      inverted: true
  - platform: gpio
    pin:
      number: GPIOXX
      inverted: true

# Twelve LED bar graph
output:
  - platform: gpio
    pin: GPIO36
    id: led_1
  - platform: gpio
    pin: GPIO39
    id: led_2
  - platform: gpio
    pin: GPIO34
    id: led_3
  - platform: gpio
    pin: GPIO35
    id: led_4
  - platform: gpio
    pin: GPIO32
    id: led_5
  - platform: gpio
    pin: GPIO33
    id: led_6
  - platform: gpio
    pin: GPIO25
    id: led_7
  - platform: gpio
    pin: GPIO27
    id: led_8
  - platform: gpio
    pin: GPIO14
    id: led_9
  - platform: gpio
    pin: GPIO14
    id: led_10
  - platform: gpio
    pin: GPIO12
    id: led_11
  - platform: gpio
    pin: GPIO13
    id: led_12

switch:
  - platform: template
    name: "Switch 1"
      turn_on_action:
      - output.turn_on: led_1
    turn_off_action:
      - output.turn_off: led_1
  - platform: template
    name: "Switch 2"
      turn_on_action:
      - output.turn_on: led_2
    turn_off_action:
      - output.turn_off: led_2
  - platform: template
    name: "Switch 3"
      turn_on_action:
      - output.turn_on: led_3
    turn_off_action:
      - output.turn_off: led_3
- platform: template
    name: "Switch 4"
      turn_on_action:
      - output.turn_on: led_4
    turn_off_action:
      - output.turn_off: led_4



      
      