esphome:
  name: salacia

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rabbit-Hutch Fallback Hotspot"
    password: !secret hot_password

captive_portal:
    
web_server:
  port: 80 
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Sensor IP address"
    ssid:
      name: "Sensor SSID"
  - platform: version
    name: "Sensor ESPHome Version"

# main
i2c:
  sda: 21
  scl: 22
  scan: false
  id: bus_a
# frequency: 100kHz

# measure salt storage level
sensor:
  - platform: vl53l0x
    name: "VL53L0x Distance"
    address: 0x29
    update_interval: 60s
    long_range: true

# two GPIO switches to read the status of the water level sensors
switch:
  - platform: gpio
    pin:
      number: GPIOXX
      inverted: true
  - platform: gpio
    pin:
      number: GPIOXX
      inverted: true

# Twelve LED bar graph
output:
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
  - platform: gpio
    pin: GPIOXX
    id: gpio_d1
        
      
      